### ISSUE TITLE
Oracle support on MDW 6

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#109]
We should create a package called "com.centurylink.mdw.oracle" and add the ojdbc driver jar into that.  That package will be checked in to corporate GitLab in the mdw60_internal project: https://ne1itcprhas62.ne1.savvis.net/MDW_DEV/mdw60_internal

We should check that this pattern works first.  We may need a code change to allow loading third-party jdbc drivers from package classloaders.

Once we get this working, CCWF can discover and import the package from there and check it into their version control.

connection pool
[(s)20170524.13:28:01.750 ~15] Failed to connect through database connection pool
      at com.centurylink.mdw.hub.servlet.StartupListener.onStartup(StartupListener.java:128)
      at com.centurylink.mdw.hub.servlet.StartupListener.contextInitialized(StartupListener.java:78)
      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
 
com.centurylink.mdw.startup.StartupException:(code=4): Failed to connect through database connection pool
      at com.centurylink.mdw.hub.servlet.StartupListener.onStartup(StartupListener.java:128)
      at com.centurylink.mdw.hub.servlet.StartupListener.contextInitialized(StartupListener.java:78)
      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)

Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot load JDBC driver class 'oracle.jdbc.driver.OracleDriver'
      at org.apache.commons.dbcp.BasicDataSource.createConnectionFactory(BasicDataSource.java:1429)
      at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1371)
      at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)

**Comment by jbrojdeCTL** [comment]
should the oracle pkg be in mdw60_internal?  I don't believe the client JDBC driver is licensed.

**Comment by jhliptak** [comment]
You are correct – we have no license to re-distribute any third party commercial jar files – ONLY open source non-GPL libraries may be external.

John Liptak
Principal Architect
Infrastructure Architecture & Strategy
931 14th St
Denver, CO 80202
John.Liptak@CenturyLink.com<mailto:John.Liptak@CenturyLink.com>
(303) 992-9623 (work)
(303) 437-4206 (cell)

All problems in computer science can be solved by another level of indirection" – Butler Lampson

**Comment by magrawa** [comment]
John is correct. Here is the license you have to agree to, which does not give us rights to ditribute:
http://www.oracle.com/technetwork/licenses/distribution-license-152002.html

**Comment by jbrojdeCTL** [comment]
New oracle pkg has also been checked into mdw6_internal repo, containing ojdbc version 12 drivers

**Comment by jbrojdeCTL** [comment]
Existing mdwdemo 5.5 DB (mdwdevdb.dev.qintra.com:1594:mdwdev) has been upgraded to mdw6 schema for testing purposes.
