### ISSUE TITLE
Deadlock in ServiceSummary event processing

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#115]
**Update:** Reproducible in MySQL 5.5 and MariaDB.

Commit eb42cd7 contains the test case (EventInstanceDeadlock.test) to reproduce this issue.  Here's the stack trace:
```
Dependencies Wait  *** not met, setting to waiting
[(e)20170602.12:14:34.040 p208808057.17269 a3.45861] Deadlock found when trying to get lock; try restarting transaction
[(i)20170602.12:14:34.040 ~141] registered event wait event='servicesummary-update-dxoakes-170602-121347223' actInst=45859as non-recurring
[(i)20170602.12:14:34.040 ~141] return event before registration: event='servicesummary-update-dxoakes-170602-121347223' actInst=45859
com.centurylink.mdw.services.ProcessException: Deadlock found when trying to get lock; try restarting transaction
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.createEventWaitInstances(ProcessExecutorImpl.java:1733)
	at com.centurylink.mdw.services.process.ProcessExecutor.createEventWaitInstances(ProcessExecutor.java:573)
	at com.centurylink.mdw.workflow.activity.AbstractWait.registerWaitEvents(AbstractWait.java:73)
	at com.centurylink.mdw.microservice.MicroserviceDependenciesWait.handleCompletionCode(MicroserviceDependenciesWait.java:88)
	at com.centurylink.mdw.workflow.activity.event.EventWaitActivity.resume(EventWaitActivity.java:150)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.resumeActivity(ProcessEngineDriver.java:314)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:613)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvents(ProcessEngineDriver.java:574)
	at com.centurylink.mdw.services.process.InternalEventDriver.run(InternalEventDriver.java:37)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$Work.run(CommonThreadPool.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$ManagedThread.run(CommonThreadPool.java:232)
Caused by: java.sql.SQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:140)
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:252)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:278)
	at org.mariadb.jdbc.MySQLStatement.executeQuery(MySQLStatement.java:333)
	at org.mariadb.jdbc.MySQLPreparedStatement.executeQuery(MySQLPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:96)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteQuery(DatabaseAccess.java:361)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runSelect(DatabaseAccess.java:387)
	at com.centurylink.mdw.service.data.process.EngineDataAccessDB.lockEventInstance(EngineDataAccessDB.java:425)
	at com.centurylink.mdw.service.data.process.EngineDataAccessDB.recordEventWait(EngineDataAccessDB.java:596)
	at com.centurylink.mdw.service.data.process.EngineDataAccessCache.recordEventWait(EngineDataAccessCache.java:611)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.createEventWaitInstances(ProcessExecutorImpl.java:1700)
	... 13 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:992)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1046)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1028)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271)
	... 23 more
[(i)20170602.12:14:34.040 ~121] Error in registerWaitEvents - Deadlock found when trying to get lock; try restarting transaction
[(i)20170602.12:14:34.040 ~121] registered event wait event='servicesummary-update-dxoakes-170602-121347223' actInst=45861as non-recurring
[(i)20170602.12:14:34.040 ~121] return event before registration: event='servicesummary-update-dxoakes-170602-121347223' actInst=45861
```

And here's the MySQL SHOW ENGINE INNODB STATUS output:
```
mysql>  SHOW ENGINE INNODB STATUS;
| InnoDB |      |
=====================================
2017-06-02 12:16:24 23bc INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 25 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 203 srv_active, 0 srv_shutdown, 13752 srv_idle
srv_master_thread log flush and writes: 13944
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 272
OS WAIT ARRAY INFO: signal count 271
Mutex spin waits 185, rounds 4914, OS waits 157
RW-shared spins 114, rounds 3420, OS waits 114
RW-excl spins 3, rounds 72, OS waits 0
Spin rounds per wait: 26.56 mutex, 30.00 RW-shared, 24.00 RW-excl
------------------------
LATEST DETECTED DEADLOCK
------------------------
2017-06-02 12:14:34 778
*** (1) TRANSACTION:
TRANSACTION 1054895, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1184, 2 row lock(s)
MySQL thread id 18, OS thread handle 0x1770, query id 8774 localhost 127.0.0.1 mdwfs statistics
select DOCUMENT_ID, STATUS_CD,  CREATE_DT, CONSUME_DT, PRESERVE_INTERVAL from EVENT_INSTANCE  where EVENT_NAME='servicesummary-update-dxoakes-170602-121347223' for upda
te
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 149 page no 23 n bits 216 index `PRIMARY` of table `mdwfs`.`event_instance` trx id 1054895 lock_mode X locks rec but not gap waiting
Record lock, heap no 146 PHYSICAL RECORD: n_fields 12; compact format; info bits 0
 0: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 1: len 6; hex 000000101893; asc       ;;
 2: len 7; hex 55000003331bf7; asc U   3  ;;
 3: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 4: len 8; hex 800000000002f905; asc         ;;
 5: len 1; hex 83; asc  ;;
 6: len 4; hex 5931ab08; asc Y1  ;;
 7: len 5; hex 999cc4c3a0; asc      ;;
 8: len 4; hex 80000e10; asc     ;;
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;

*** (2) TRANSACTION:
TRANSACTION 1054894, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
3 lock struct(s), heap size 1184, 2 row lock(s)
MySQL thread id 17, OS thread handle 0x778, query id 8775 localhost 127.0.0.1 mdwfs statistics
select DOCUMENT_ID, STATUS_CD,  CREATE_DT, CONSUME_DT, PRESERVE_INTERVAL from EVENT_INSTANCE  where EVENT_NAME='servicesummary-update-dxoakes-170602-121347223' for upda
te
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 149 page no 23 n bits 216 index `PRIMARY` of table `mdwfs`.`event_instance` trx id 1054894 lock mode S locks rec but not gap
Record lock, heap no 146 PHYSICAL RECORD: n_fields 12; compact format; info bits 0
 0: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 1: len 6; hex 000000101893; asc       ;;
 2: len 7; hex 55000003331bf7; asc U   3  ;;
 3: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 4: len 8; hex 800000000002f905; asc         ;;
 5: len 1; hex 83; asc  ;;
 6: len 4; hex 5931ab08; asc Y1  ;;
 7: len 5; hex 999cc4c3a0; asc      ;;
 8: len 4; hex 80000e10; asc     ;;
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 149 page no 23 n bits 216 index `PRIMARY` of table `mdwfs`.`event_instance` trx id 1054894 lock_mode X locks rec but not gap waiting
Record lock, heap no 146 PHYSICAL RECORD: n_fields 12; compact format; info bits 0
 0: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 1: len 6; hex 000000101893; asc       ;;
 2: len 7; hex 55000003331bf7; asc U   3  ;;
 3: len 30; hex 7365727669636573756d6d6172792d7570646174652d64786f616b65732d; asc servicesummary-update-dxoakes-; (total 46 bytes);
 4: len 8; hex 800000000002f905; asc         ;;
 5: len 1; hex 83; asc  ;;
 6: len 4; hex 5931ab08; asc Y1  ;;
 7: len 5; hex 999cc4c3a0; asc      ;;
 8: len 4; hex 80000e10; asc     ;;
 9: SQL NULL;
 10: SQL NULL;
 11: SQL NULL;

*** WE ROLL BACK TRANSACTION (2)
------------
TRANSACTIONS
------------
Trx id counter 1054904
Purge done for trx's n:o < 1054901 undo n:o < 0 state: running but idle
History list length 1202
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 0, not started
MySQL thread id 19, OS thread handle 0x23bc, query id 8833 localhost 127.0.0.1 root init
SHOW ENGINE INNODB STATUS
---TRANSACTION 1054902, not started
MySQL thread id 18, OS thread handle 0x1770, query id 8825 localhost 127.0.0.1 mdwfs cleaning up
---TRANSACTION 1054903, not started
MySQL thread id 17, OS thread handle 0x778, query id 8831 localhost 127.0.0.1 mdwfs cleaning up
---TRANSACTION 1054598, not started
MySQL thread id 5, OS thread handle 0x570, query id 7279 localhost 127.0.0.1 mdwfs cleaning up
--------
FILE I/O
--------
I/O thread 0 state: wait Windows aio (insert buffer thread)
I/O thread 1 state: wait Windows aio (log thread)
I/O thread 2 state: wait Windows aio (read thread)
I/O thread 3 state: wait Windows aio (read thread)
I/O thread 4 state: wait Windows aio (read thread)
I/O thread 5 state: wait Windows aio (read thread)
I/O thread 6 state: wait Windows aio (write thread)
I/O thread 7 state: wait Windows aio (write thread)
I/O thread 8 state: wait Windows aio (write thread)
I/O thread 9 state: wait Windows aio (write thread)
Pending normal aio reads: 0 [0, 0, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
 ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
867 OS file reads, 3658 OS file writes, 1530 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 0.00 writes/s, 0.00 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 0, seg size 2, 11 merges
merged operations:
 insert 12, delete mark 0, delete 0
discarded operations:
 insert 0, delete mark 0, delete 0
Hash table size 276707, node heap has 8 buffer(s)
0.00 hash searches/s, 0.00 non-hash searches/s
---
LOG
---
Log sequence number 1011277154
Log flushed up to   1011277154
Pages flushed up to 1011277154
Last checkpoint at  1011277154
0 pending log writes, 0 pending chkp writes
963 log i/o's done, 0.00 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total memory allocated 137428992; in additional pool allocated 0
Dictionary memory allocated 161978
Buffer pool size   8192
Free buffers       7323
Database pages     861
Old database pages 333
Modified db pages  0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 0, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 838, created 23, written 2578
0.00 reads/s, 0.00 creates/s, 0.00 writes/s
No buffer pool page gets since the last printout
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 861, unzip_LRU len: 0
I/O sum[0]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
0 read views open inside InnoDB
Main thread id 1464, state: sleeping
Number of rows inserted 1117, updated 182, deleted 142, read 542905
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 0.00 reads/s
----------------------------
END OF INNODB MONITOR OUTPUT
============================
```

Also see attached.
[sdwf_deadlock.txt](https://github.com/CenturyLinkCloud/mdw/files/1048271/sdwf_deadlock.txt)

MariaDB monitor output:
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 5.5.5-10.0.13-MariaDB mariadb.org binary distribution
...
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 116
OS WAIT ARRAY INFO: signal count 115
Mutex spin waits 971, rounds 3855, OS waits 81
RW-shared spins 35, rounds 1050, OS waits 34
RW-excl spins 1, rounds 30, OS waits 1
Spin rounds per wait: 3.97 mutex, 30.00 RW-shared, 30.00 RW-excl
------------------------
LATEST DETECTED DEADLOCK
------------------------
2017-06-08 13:43:57 2ffc
*** (1) TRANSACTION:
TRANSACTION 21123, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 312, 2 row lock(s)
MySQL thread id 8, OS thread handle 0x22e0, query id 1747 localhost 127.0.0.1 mdw statistics
select DOCUMENT_ID, STATUS_CD,  CREATE_DT, CONSUME_DT, PRESERVE_INTERVAL from EVENT_INSTANCE  where EVENT_NAME='servicesummary-update-dxoakes-170608-134244590' for upda
te
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 31 page no 3 n bits 136 index `PRIMARY` of table `mdw`.`event_instance` trx id 21123 lock_mode X locks rec but not gap waiting
*** (2) TRANSACTION:
TRANSACTION 21122, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
3 lock struct(s), heap size 312, 2 row lock(s)
MySQL thread id 5, OS thread handle 0x2ffc, query id 1749 localhost 127.0.0.1 mdw statistics
select DOCUMENT_ID, STATUS_CD,  CREATE_DT, CONSUME_DT, PRESERVE_INTERVAL from EVENT_INSTANCE  where EVENT_NAME='servicesummary-update-dxoakes-170608-134244590' for upda
te
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 31 page no 3 n bits 136 index `PRIMARY` of table `mdw`.`event_instance` trx id 21122 lock mode S locks rec but not gap
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 31 page no 3 n bits 136 index `PRIMARY` of table `mdw`.`event_instance` trx id 21122 lock_mode X locks rec but not gap waiting
*** WE ROLL BACK TRANSACTION (2)
------------
TRANSACTIONS
------------
Trx id counter 21141
Purge done for trx's n:o < 21141 undo n:o < 0 state: running but idle
History list length 1032
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 0, not started
MySQL thread id 10, OS thread handle 0x276c, query id 1834 localhost 127.0.0.1 root init
SHOW ENGINE INNODB STATUS
---TRANSACTION 21123, not started
MySQL thread id 8, OS thread handle 0x276c, query id 1784 localhost 127.0.0.1 mdw cleaning up
---TRANSACTION 21132, not started
MySQL thread id 7, OS thread handle 0x22e0, query id 1832 localhost 127.0.0.1 mdw cleaning up
---TRANSACTION 21119, not started
MySQL thread id 6, OS thread handle 0x2ffc, query id 1746 localhost 127.0.0.1 mdw cleaning up
```

**Comment by donaldoakes** [comment]
With the broadcast events paradigm in mdw6 we've introduced a higher likelihood of db contention on the EVENT_INSTANCE table.  In fact contention is almost guaranteed if a master process instance launches many fast-running subflows that all listen for the same EVENT_NAME primary key.  Unlike Oracle, the INNO DB engine in MySQL can deadlock on competing "SELECT ... FOR UPDATE" statements where the criterion is a primary key, especially if a SELECT is preceeded by in INSERT in the same table/key within the same transaction:
https://dev.mysql.com/doc/refman/5.5/en/innodb-deadlocks.html

The [MySQL documentation](https://dev.mysql.com/doc/refman/5.5/en/innodb-deadlocks-handling.html) suggests an approach to avoiding this using programmatic mutexes, which is what we've done with the new BroadcastEventLockCache class.  This fix is reliable for service processes where in-VM execution is the cause of racing event wait instances.  However, for long-running processes we need to investigate a db-centered or other approach that can lock across Java virtual machines.  Issue #122 has been created to track this.
