### ISSUE TITLE
Postman autotests fail on old Linux versions

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#153]
Stack trace below.  Not worth fixing unless reproducible in EWS.

Related to issue #154 in AppFog.

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.centurylink.mdw.services.test.TestCaseRun.run(TestCaseRun.java:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: J2V8 native library not loaded
        at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:252)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:152)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:128)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:84)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:48)
        at com.centurylink.mdw.testing.postman.NodeRunner.run(NodeRunner.java:53)
        ... 8 more
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
        no libj2v8_linux_x86_64.so in java.library.path
        no j2v8_linux_x86_64 in java.library.path
        /home/wlsmdt/libj2v8_linux_x86_64.so: /home/wlsmdt/libj2v8_linux_x86_64.so: ELF file OS ABI invalid

        at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:79)
        at com.eclipsesource.v8.V8.load(V8.java:74)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:148)
        ... 12 more
```

**Comment by donaldoakes** [comment]
We'll try a custom build of j2v8 with static linking of libstdc++.
