### ISSUE TITLE
Postman autotests fail on Cloud Foundry (at least AppFog)

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#154]
Probably it's not feasible to invoke native shared libraries on Cloud Foundry.  We may need to think of an alternative approach for executing NodeJS in these environments.  Possibly we'll need to incorporate portions of the NodeJS buildpack:
https://github.com/cloudfoundry/nodejs-buildpack

```
2017-07-19T11:17:26.92-0600 [App/0]      OUT [(d)20170719.17:17:26.922 ~165] Loading Dynamic Java byte code from: string:///com/centurylink/mdw/testing/postman/NodeRunn
er.java
2017-07-19T11:17:27.15-0600 [App/0]      ERR java.lang.reflect.InvocationTargetException
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:498)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.centurylink.mdw.services.test.TestCaseRun.run(TestCaseRun.java:210)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at java.lang.Thread.run(Thread.java:745)
2017-07-19T11:17:27.15-0600 [App/0]      ERR Caused by: java.lang.IllegalStateException: J2V8 native library not loaded
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:252)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.V8.createV8Runtime(V8.java:152)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.V8.createV8Runtime(V8.java:128)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:84)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:48)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    ... 8 more
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.centurylink.mdw.testing.postman.NodeRunner.run(NodeRunner.java:53)
2017-07-19T11:17:27.15-0600 [App/0]      ERR Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
2017-07-19T11:17:27.15-0600 [App/0]      ERR    no libj2v8_linux_x86_64.so in java.library.path
2017-07-19T11:17:27.15-0600 [App/0]      ERR    no j2v8_linux_x86_64 in java.library.path
2017-07-19T11:17:27.15-0600 [App/0]      ERR    /home/vcap/libj2v8_linux_x86_64.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required
 by /home/vcap/libj2v8_linux_x86_64.so)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:79)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.V8.load(V8.java:74)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    at com.eclipsesource.v8.V8.createV8Runtime(V8.java:148)
2017-07-19T11:17:27.15-0600 [App/0]      ERR    ... 12 more
```

**Comment by donaldoakes** [comment]
Fixed by adding updated libstdc++ shared library to LD_LIBRARY_PATH (in asset package com.centurylink.mdw.node).
