### ISSUE TITLE
Fix mdw version in mdw-cli when using SNAPSHOT build

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#202]
mdw init --mdw-version 6.0.06-SNAPSHOT my-mdw

Initializing my-mdw...
Retrieving templates: mdw-templates-6.0.06-SNAPSHOT.zip
Exception in thread "main" java.io.FileNotFoundException: http://repo.maven.apac
he.org/maven2/com/centurylink/mdw/mdw-templates/6.0.06-SNAPSHOT/mdw-templates-6.
0.06-SNAPSHOT.zip
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLCo
nnection.java:1835)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLCon
nection.java:1440)
        at java.net.URL.openStream(URL.java:1038)
        at com.centurylink.mdw.cli.Download.run(Download.java:55)
        at com.centurylink.mdw.cli.Init.run(Init.java:113)
        at com.centurylink.mdw.cli.Main.main(Main.java:61)

**Comment by magrawa** [comment]
init  --snapshots   --mdw-version 6.0.06-SNAPSHOT my-mdw
This does not work with SNAPSHOTS on 143. It works only with oss.sonatype.org

https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.centurylink.mdw&a=mdw-templates&v=LATEST&p=zip
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.centurylink.mdw&a=mdw-templates&v=6.0.06-SNAPSHOT&p=zip

Note: To get latest on formal release 
https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=com.centurylink.mdw&a=mdw-templates&v=LATEST&p=zip
