### ISSUE TITLE
MDW-hub’s variables section for process not renter properly

### ISSUE THREAD

**Issue by jlarance** [CenturyLinkCloud/mdw#212]
In MDW-hub’s variables section for process not renter properly if a JSON variable receives a non-json message as response.
Ex: For improve webservice call, expected value is JSON message, but they return “Page not Found” as response which is not json.

http://tomwf-dev1.pcfomactl.dev.intranet/mdw/#/workflow/processes/340133

Log:-

2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] Caused by: com.centurylink.mdw.translator.TranslationException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.common.translator.impl.JsonObjectTranslator.realToObject(JsonObjectTranslator.java:32)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.model.variable.Document.getObject(Document.java:49)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.getContext(WorkflowServicesImpl.java:414)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.getProcessValues(WorkflowServicesImpl.java:329)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.service.rest.Processes.get(Processes.java:112)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] ... 41 more
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:745)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.translator.VariableTranslator.realToObject(VariableTranslator.java:169)
2017-09-12T11:19:29.885-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.getProcessValues(WorkflowServicesImpl.java:325)
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.common.translator.impl.JsonObjectTranslator.realToObject(JsonObjectTranslator.java:30)
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] ... 47 more
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] Caused by: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] at org.json.JSONObject.<init>(JSONObject.java:195)
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] at org.json.JSONObject.<init>(JSONObject.java:319)
2017-09-12T11:19:29.886-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.model.JsonObject.<init>(JsonObject.java:34)
2017-09-12T11:19:29.893-06:00 [RTR/2] [OUT] tomwf-dev1.pcfomactl.dev.intranet - [2017-09-12T17:19:29.882+0000] "GET /mdw/Services/Processes/340104/summary?app=mdw-admin HTTP/1.1" 200 0 183 "http://tomwf-dev1.pcfomactl.dev.intranet/mdw/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "151.117.164.7:51938" "151.117.164.65:61168" x_forwarded_for:"10.188.217.74" x_forwarded_proto:"http" vcap_request_id:"954d250b-4982-442b-5629-cfb3cbbe96c3" response_time:0.010544087 app_id:"d7d0ae24-6889-40f0-b4ca-999136b62813" app_index:"0" x_b3_traceid:"aa00e4658fb4cf8e" x_b3_spanid:"aa00e4658fb4cf8e" x_b3_parentspanid:"-"
2017-09-12T11:19:29.898-06:00 [RTR/1] [OUT] tomwf-dev1.pcfomactl.dev.intranet - [2017-09-12T17:19:29.882+0000] "GET /mdw/Services/Processes/340104/values?app=mdw-admin HTTP/1.1" 500 0 109 "http://tomwf-dev1.pcfomactl.dev.intranet/mdw/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "151.117.164.7:51937" "151.117.164.65:61168" x_forwarded_for:"10.188.217.74" x_forwarded_proto:"http" vcap_request_id:"8fd068dc-b212-4f85-7126-d6857c763018" response_time:0.015532578 app_id:"d7d0ae24-6889-40f0-b4ca-999136b62813" app_index:"0" x_b3_traceid:"dfe65c4653e3b5c7" x_b3_spanid:"dfe65c4653e3b5c7" x_b3_parentspanid:"-"
2017-09-12T11:19:35.444-06:00 [APP/PROC/WEB/0] [OUT] [(s)20170912.12:19:35.444 ~87] A JSONObject text must begin with '{' at 1 [character 2 line 1]
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:93)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.service.rest.Processes.get(Processes.java:241)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] com.centurylink.mdw.common.service.ServiceException:(code=500): A JSONObject text must begin with '{' at 1 [character 2 line 1]
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:191)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:358)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:189)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.common.translator.impl.JsonObjectTranslator.realToObject(JsonObjectTranslator.java:32)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.model.variable.Document.getObject(Document.java:49)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.getContext(WorkflowServicesImpl.java:414)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.getProcessValue(WorkflowServicesImpl.java:374)
2017-09-12T11:19:35.445-06:00 [APP/PROC/WEB/0] [OUT] ... 41 more

**Comment by donaldoakes** [comment]
Fixed with commit: 96faabc
This fix prevents one unparseable document variable from wrecking the entire Values display.  However, the unparseable value still will not be displayed since its value cannot be assigned.  To see the raw data for an unparseable value, you must still refer to the adapter request/response.
