### ISSUE TITLE
Ugly startup exception when running locally with project created via "mdw init"

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#227]
Users see the exception below when following the [Quick-start guide](http://centurylinkcloud.github.io/mdw/docs/getting-started/quick-start/).  Somehow we should determine that the user is running locally and refrain from attempting to clone.  Or else we can revert the change to automatically clone when the local git repo is missing.
```
[(i)20171004.09:56:48.410 ~12] Loading assets from path: assets
[(s)20171004.09:56:48.410 ~12] **** WARNING: Git location . does not contain a repository.  Cloning: https://github.com/CenturyLinkCloud/mdw-demo.git
[(s)20171004.09:56:48.676 ~12] Error during Git up-to-date check.
org.eclipse.jgit.api.errors.JGitInternalException: Destination path "." already exists and is not an empty directory
        at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:143)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:124)
        at com.centurylink.mdw.dataaccess.file.VersionControlGit.cloneNoCheckout(VersionControlGit.java:610)
        at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:156)
        at com.centurylink.mdw.dataaccess.DataAccess.getVcsProcessLoader(DataAccess.java:109)
        at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:63)
        at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:71)
        at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:72)
        at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:60)
        at com.centurylink.mdw.cache.impl.PackageCache.getPackage(PackageCache.java:201)
        at com.centurylink.mdw.dataaccess.EmbeddedDataAccess.create(EmbeddedDataAccess.java:55)
        at com.centurylink.mdw.dataaccess.DatabaseAccess.checkAndStartEmbeddedDb(DatabaseAccess.java:185)
        at com.centurylink.mdw.dataaccess.DatabaseAccess.<init>(DatabaseAccess.java:142)
        at com.centurylink.mdw.hub.MdwMain.startup(MdwMain.java:86)
        at com.centurylink.mdw.hub.StartupListener.contextInitialized(StartupListener.java:37)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4743)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by donaldoakes** [comment]
Fixed this by omitting any default mdw.git.user.
