### ISSUE TITLE
Editing a new file in MDW Hub

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#252]
Steps to reproduce

1. Create a new test asset (or any asset)
2. Do not commit to Git
3. Go to MDW Hub and edit the file.
4. Unselect all of the options (Do not commit to Git, No cache refresh and not propagation, overwrite existing version)
5. Try to save and you get this error

[(s)20171109.09:40:42.911 ~94] Commit Info not found: GitVcs/com.centurylink.mdw.kafka/KafkaProducer.test
com.centurylink.mdw.common.service.ServiceException:(code=404): Commit Info not found: GitVcs/com.centurylink.mdw.kafka/KafkaProducer.test
	at com.centurylink.mdw.service.rest.GitVcs.get(GitVcs.java:93)
	at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:95)
	at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:58)
	at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:191)
	at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:358)
	at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:238)
	at com.centurylink.mdw.hub.servlet.RestServlet.doGet(RestServlet.java:77)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:208)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[(s)20171109.09:42:57.836 ~91] Failed to get user: null
com.centurylink.mdw.cache.CachingException: Failed to get user: null
	at com.centurylink.mdw.service.data.task.UserGroupCache.loadUser(UserGroupCache.java:339)
	at com.centurylink.mdw.service.data.task.UserGroupCache.getUser0(UserGroupCache.java:235)
	at com.centurylink.mdw.service.data.task.UserGroupCache.getUser(UserGroupCache.java:140)
	at com.centurylink.mdw.hub.servlet.AssetContentServlet.authorizeForUpdate(AssetContentServlet.java:369)
	at com.centurylink.mdw.hub.servlet.AssetContentServlet.doPut(AssetContentServlet.java:246)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:649)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: Failed to get user: null
	at com.centurylink.mdw.dataaccess.db.UserDataAccessDb.getUser(UserDataAccessDb.java:66)
	at com.centurylink.mdw.services.user.UserManagerBean.getUser(UserManagerBean.java:46)
	at com.centurylink.mdw.service.data.task.UserGroupCache.loadUser(UserGroupCache.java:336)
	... 32 more
Caused by: java.lang.NullPointerException
	at com.centurylink.mdw.dataaccess.db.UserDataAccessDb.getUser(UserDataAccessDb.java:55)
	... 34 more

**Comment by magrawa** [comment]
Not reproducible
