### ISSUE TITLE
Execute CLI Checkpoint on server startup

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#265]
This will ensure that ASSET_REFs are always up-to-date with the latest assets on the file system.  This will prevent inflight issues related to unfound process ids as in the stack trace below.
```
2017-11-29T09:03:50.007-07:00 [APP/PROC/WEB/0] [OUT] [(d)20171129.10:03:50.007 ~100] ** - new HTTP session from: 151.117.164.51
2017-11-29T09:03:50.020-07:00 [APP/PROC/WEB/0] [OUT] [(i)20171129.10:03:50.019 ~100] Register cache ProcessCache
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] [(s)20171129.10:03:50.038 ~100] Process ID not found: 163016976
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.service.rest.Workflow.get(Workflow.java:82)
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:58)
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:191)
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] com.centurylink.mdw.common.service.ServiceException:(code=404): Process ID not found: 163016976
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:95)
2017-11-29T09:03:50.038-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:358)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.RestServlet.doGet(RestServlet.java:77)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:238)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:208)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:440)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:745)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:247)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
2017-11-29T09:03:50.039-07:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-11-29T09:03:50.046-07:00 [RTR/1] [OUT] tomwf-dev1.pcfomactl.dev.intranet - [2017-11-29T16:03:50.003+0000] "GET /mdw/Services/Workflow?id=163016976 HTTP/1.1" 404 0 77 "-" "Java/1.8.0_91" "151.117.164.7:50730" "151.117.164.60:62050" x_forwarded_for:"10.1.214.25" x_forwarded_proto:"http" vcap_request_id:"1ca48282-a605-402b-7c95-64400f0ddb97" response_time:0.04244643 app_id:"d7d0ae24-6889-40f0-b4ca-999136b62813" app_index:"0" x_b3_traceid:"5dc39f43d7ce71eb" x_b3_spanid:"5dc39f43d7ce71eb" x_b3_parentspanid:"-"
```

**Comment by jbrojdeCTL** [comment]
MDW instance will automatically update ASSET_REF DB table upon startup unless either of the following conditions apply:
1) The property "mdw.git.auto.pull" is set to true (because that will trigger an auto-import which will update ASSET_REF)
2) The instance is running in "dev" mode (system property mdw.runtime.env=dev)
