### ISSUE TITLE
Global transaction backoff/retry for MySQL/MariaDB

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#273]
Lately I've been seeing stack traces like the following when executing the Create Bug flow in mdw-demo.

I really think we need to implement global backoff/retry as recommended for InnoDB.

```
com.centurylink.mdw.activity.ActivityException: Error creating task com.centurylink.mdw.demo.bugs/ResolveBugCustom.task
Caused by: org.mariadb.jdbc.internal.common.QueryException: Deadlock found when trying to get lock; try restarting transaction
org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:992)
org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1046)
org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1028)
org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271)
org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:348)
org.mariadb.jdbc.MySQLPreparedStatement.executeUpdate(MySQLPreparedStatement.java:149)
org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteUpdate(DatabaseAccess.java:316)
com.centurylink.mdw.dataaccess.DatabaseAccess.runUpdateWithPreparedStatement(DatabaseAccess.java:424)
com.centurylink.mdw.service.data.task.TaskDataAccess.setTaskInstanceGroups(TaskDataAccess.java:446)
com.centurylink.mdw.services.task.TaskWorkflowHelper.createTaskInstance(TaskWorkflowHelper.java:204)
com.centurylink.mdw.services.task.TaskWorkflowHelper.createTaskInstance(TaskWorkflowHelper.java:127)
com.centurylink.mdw.services.task.TaskServicesImpl.createTask(TaskServicesImpl.java:87)
com.centurylink.mdw.demo.bugs.PersistBugActivity.execute(PersistBugActivity.java:42)
com.centurylink.mdw.services.process.BaseActivity.execute(BaseActivity.java:224)
com.centurylink.mdw.services.process.BaseActivity.executeTimed(BaseActivity.java:243)
com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:379)
com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:612)
com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:834)
com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:741)
com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:679)
com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:933)
com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:267)
demo.api.Bugs.post(Bugs.java:39)
com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:102)
com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:62)
com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:191)
com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:386)
com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:243)
com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:128)
javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:208)
javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
com.centurylink.mdw.hub.servlet.AccessFilter.doFilter
```

**Comment by donaldoakes** [comment]
Here's some information about deadlocks in InnoDB:
https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks.html

We should give strong consideration to Spring Retry:
https://github.com/spring-projects/spring-retry

**Comment by vimala-nagarja-CTL** [comment]
Steps to reproduce the issue:
1. From MDW hub http Poster tab,  post 5 to 6 consecutive messages using 
 URL http://localhost:8080/mdw/services/demo/api/bugs.
Body of the message:
    {
  "title": "This is a good bug",
  "description": "Whatever that means"
   }

2.    Restful service  Bugs,  invokes 'Create Bug' Process
3. Deadlock occurs, in the method setTaskInstanceGroups. Below is the stack trace:

(s)20180206.13:02:07.648 ~90] Error creating task com.centurylink.mdw.demo.bugs/ResolveBugCustom.task
com.centurylink.mdw.common.service.ServiceException:(code=500): Error creating task com.centurylink.mdw.demo.bugs/ResolveBugCustom.task
	at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:961)
	at com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:267)
	at demo.api.Bugs.post(Bugs.java:45)
	at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:102)
	at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:62)
	at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:191)
	at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:386)
	at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:260)
	at com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:145)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:247)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1524)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.centurylink.mdw.activity.ActivityException: Error creating task com.centurylink.mdw.demo.bugs/ResolveBugCustom.task
	at com.centurylink.mdw.demo.bugs.PersistBugActivity.execute(PersistBugActivity.java:60)
	at com.centurylink.mdw.services.process.BaseActivity.execute(BaseActivity.java:224)
	at com.centurylink.mdw.services.process.BaseActivity.executeTimed(BaseActivity.java:243)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:380)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:613)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:848)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:755)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:693)
	at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:933)
	... 38 more
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: failed to associate task instance groups
	at com.centurylink.mdw.service.data.task.TaskDataAccess.setTaskInstanceGroups(TaskDataAccess.java:451)
	at com.centurylink.mdw.services.task.TaskWorkflowHelper.createTaskInstance(TaskWorkflowHelper.java:205)
	at com.centurylink.mdw.services.task.TaskWorkflowHelper.createTaskInstance(TaskWorkflowHelper.java:127)
	at com.centurylink.mdw.services.task.TaskServicesImpl.createTask(TaskServicesImpl.java:87)
	at com.centurylink.mdw.demo.bugs.PersistBugActivity.execute(PersistBugActivity.java:42)
	... 46 more
Caused by: java.sql.SQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:140)
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:252)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:278)
	at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:348)
	at org.mariadb.jdbc.MySQLPreparedStatement.executeUpdate(MySQLPreparedStatement.java:149)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteUpdate(DatabaseAccess.java:338)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runUpdateWithPreparedStatement(DatabaseAccess.java:446)
	at com.centurylink.mdw.service.data.task.TaskDataAccess.setTaskInstanceGroups(TaskDataAccess.java:446)
	... 50 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: Deadlock found when trying to get lock; try restarting transaction
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:992)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1046)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1028)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271)
	... 57 more
