### ISSUE TITLE
ASSET_REF update issue on non-dev embedded db environment

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#276]
When using embedded db, it seems that the asset ref check in DataAccess is premature since the database is not available yet.  Maybe the solution is to avoid the asset ref check for embedded db.
```
[(s)20171218.15:34:40.300 ~18] Error during Git up-to-date check.
com.centurylink.mdw.dataaccess.DataAccessException: Cannot create PoolableConnectionFactory (Could not connect to address=(host=localhost)(port=3308)(type=master) : Connection refused: connect)
	at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:207)
	at com.centurylink.mdw.dataaccess.DataAccess.getVcsProcessLoader(DataAccess.java:112)
	at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:66)
	at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:74)
	at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:72)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:60)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackage(PackageCache.java:201)
	at com.centurylink.mdw.dataaccess.EmbeddedDataAccess.create(EmbeddedDataAccess.java:55)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.checkAndStartEmbeddedDb(DatabaseAccess.java:186)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.<init>(DatabaseAccess.java:143)
	at com.centurylink.mdw.hub.MdwMain.startup(MdwMain.java:76)
	at com.centurylink.mdw.hub.StartupListener.contextInitialized(StartupListener.java:40)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (Could not connect to address=(host=localhost)(port=3308)(type=master) : Connection refused: connect)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.openConnection(DatabaseAccess.java:210)
	at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:202)
	... 24 more
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3308)(type=master) : Connection refused: connect
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:136)
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
	at org.mariadb.jdbc.Driver.connect(Driver.java:107)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
	... 28 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not connect to address=(host=localhost)(port=3308)(type=master) : Connection refused: connect
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connectWithoutProxy(MySQLProtocol.java:631)
	at org.mariadb.jdbc.internal.common.Utils.retrieveProxy(Utils.java:541)
	at org.mariadb.jdbc.Driver.connect(Driver.java:102)
	... 32 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:289)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connectWithoutProxy(MySQLProtocol.java:626)
	... 34 more
```

**Comment by jbrojdeCTL** [comment]
Leave a comment
