### ISSUE TITLE
Cloud Foundry integration for FilePanel

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#302]
Different connectivity issues in PCF vs AppFog.  Probably we should move CfLogListener.java and its dependencies to a separate asset package.  We may need to centralize log collection for PaaS environments.

Other points:
 - Max size/rolling

Here's the current stack trace from AppFog:
```
2018-01-23T14:24:02.05-0700 [App/0]      OUT [(i)20180123.21:24:02.056 ~13] Running startup service class com.centurylink.mdw.system.filepanel.CfLogListener
2018-01-23T14:24:02.06-0700 [App/0]      OUT [(i)20180123.21:24:02.060 ~13] Connecting to Cloud Foundry API: https://api.useast.appfog.ctl.io
2018-01-23T14:24:07.71-0700 [App/0]      OUT [(i)20180123.21:24:07.718 ~13] MDW initialization completed after 24996 ms
2018-01-23T14:24:08.06-0700 [App/0]      ERR Exception in thread "LogCollector" org.cloudfoundry.client.lib.CloudOperationException: javax.websocket.DeploymentException
: The HTTP response from the server [404] did not permit the HTTP upgrade to WebSocket
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.cloudfoundry.client.lib.rest.LoggregatorClient.connectToLoggregator(LoggregatorClient.java:67)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.streamLoggregatorLogs(CloudControllerClientImpl.java:2252)

2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.cloudfoundry.client.lib.rest.CloudControllerClientImpl.streamLogs(CloudControllerClientImpl.java:254)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.cloudfoundry.client.lib.CloudFoundryClient.streamLogs(CloudFoundryClient.java:376)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at com.centurylink.mdw.system.filepanel.CfLogListener$1.run(CfLogListener.java:84)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at java.lang.Thread.run(Thread.java:745)
2018-01-23T14:24:08.06-0700 [App/0]      ERR Caused by: javax.websocket.DeploymentException: The HTTP response from the server [404] did not permit the HTTP upgrade to
WebSocket
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServerRecursive(WsWebSocketContainer.java:465)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:225)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    at org.cloudfoundry.client.lib.rest.LoggregatorClient.connectToLoggregator(LoggregatorClient.java:64)
2018-01-23T14:24:08.06-0700 [App/0]      ERR    ... 5 more
2018-01-23T14:24:14.58-0700 [App/0]      OUT [CONTAINER] org.apache.catalina.startup.HostConfig             INFO    Deployment of web application archive /home/vcap/app
/.java-buildpack/tomcat/webapps/mdw.war has finished in 35,909 ms
```

**Comment by donaldoakes** [comment]
The CF integration impl has been removed from package system.filepanel on master.  Attached for future reference if/when this issue is addressed.
[filepanel.zip](https://github.com/CenturyLinkCloud/mdw/files/1790158/filepanel.zip)
