### ISSUE TITLE
Activity timeout invalid event instance delete query

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#348]
Uncovered through email verification timeout in MDW Central.  Here's the stack trace:
```
[(i)20180301.11:34:01.063 ~46] EventScheduler processes event InternalEvent.10018timeout
[(i)20180301.11:34:01.063 ~138] EngineDriver.T138 - starts processing
[(d)20180301.11:34:01.063 ~138] executeFlow: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>DELAY</EventType><WorkType>ACTIVITY</WorkType><WorkId>9</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>10018</WorkInstanceId><WorkOwnerId>10004</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><SecondaryWorkOwnerId>1</SecondaryWorkOwnerId><SecondaryWorkOwnerType>SLA</SecondaryWorkOwnerType><MasterRequestId>28005133-161ddb077e2</MasterRequestId></EventMessage>
[(s)20180301.11:34:01.598 ~138] Unable to load process id 165193213 (instance id=10004) for null (event will be deleted)
[(s)20180301.11:34:01.973 ~138] Failed to delete internal eventnull
com.centurylink.mdw.dataaccess.DataAccessException: Failed to delete internal eventnull
	at com.centurylink.mdw.services.process.ProcessExecutor.deleteInternalEvent(ProcessExecutor.java:818)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvents(ProcessEngineDriver.java:535)
	at com.centurylink.mdw.services.process.InternalEventDriver.run(InternalEventDriver.java:37)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$Work.run(CommonThreadPool.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$ManagedThread.run(CommonThreadPool.java:232)
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: Failed to delete internal eventnull
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.deleteInternalEvent(ProcessExecutorImpl.java:441)
	at com.centurylink.mdw.services.process.ProcessExecutor.deleteInternalEvent(ProcessExecutor.java:811)
	... 7 more
Caused by: java.sql.SQLException: You need to set exactly 1 parameters on the prepared statement
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149)
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:252)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:278)
	at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:348)
	at org.mariadb.jdbc.MySQLPreparedStatement.executeUpdate(MySQLPreparedStatement.java:149)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteUpdate(DatabaseAccess.java:348)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runUpdate(DatabaseAccess.java:412)
	at com.centurylink.mdw.service.data.process.EngineDataAccessDB.deleteEventInstance(EngineDataAccessDB.java:505)
	at com.centurylink.mdw.service.data.process.EngineDataAccessCache.deleteEventInstance(EngineDataAccessCache.java:754)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.deleteInternalEvent(ProcessExecutorImpl.java:438)
	... 8 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: You need to set exactly 1 parameters on the prepared statement
	at org.mariadb.jdbc.internal.common.query.MySQLParameterizedQuery.validate(MySQLParameterizedQuery.java:137)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1032)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1028)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271)
	... 17 more
[(i)20180301.11:40:01.166 ~46] EventScheduler processes event InternalEvent.10021timeout
[(i)20180301.11:40:01.166 ~143] EngineDriver.T143 - starts processing
[(d)20180301.11:40:01.166 ~143] executeFlow: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>DELAY</EventType><WorkType>ACTIVITY</WorkType><WorkId>9</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>10021</WorkInstanceId><WorkOwnerId>10005</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><SecondaryWorkOwnerId>1</SecondaryWorkOwnerId><SecondaryWorkOwnerType>SLA</SecondaryWorkOwnerType><MasterRequestId>28005133-161ddb664f3</MasterRequestId></EventMessage>
[(s)20180301.11:40:01.636 ~143] Unable to load process id 165193213 (instance id=10005) for null (event will be deleted)
[(s)20180301.11:40:01.636 ~143] Failed to delete internal eventnull
com.centurylink.mdw.dataaccess.DataAccessException: Failed to delete internal eventnull
	at com.centurylink.mdw.services.process.ProcessExecutor.deleteInternalEvent(ProcessExecutor.java:818)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvents(ProcessEngineDriver.java:535)
	at com.centurylink.mdw.services.process.InternalEventDriver.run(InternalEventDriver.java:37)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$Work.run(CommonThreadPool.java:263)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.centurylink.mdw.container.plugin.CommonThreadPool$ManagedThread.run(CommonThreadPool.java:232)
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: Failed to delete internal eventnull
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.deleteInternalEvent(ProcessExecutorImpl.java:441)
	at com.centurylink.mdw.services.process.ProcessExecutor.deleteInternalEvent(ProcessExecutor.java:811)
	... 7 more
Caused by: java.sql.SQLException: You need to set exactly 1 parameters on the prepared statement
	at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:149)
	at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
	at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:252)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:278)
	at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:348)
	at org.mariadb.jdbc.MySQLPreparedStatement.executeUpdate(MySQLPreparedStatement.java:149)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:98)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteUpdate(DatabaseAccess.java:348)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runUpdate(DatabaseAccess.java:412)
	at com.centurylink.mdw.service.data.process.EngineDataAccessDB.deleteEventInstance(EngineDataAccessDB.java:505)
	at com.centurylink.mdw.service.data.process.EngineDataAccessCache.deleteEventInstance(EngineDataAccessCache.java:754)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.deleteInternalEvent(ProcessExecutorImpl.java:438)
	... 8 more
Caused by: org.mariadb.jdbc.internal.common.QueryException: You need to set exactly 1 parameters on the prepared statement
	at org.mariadb.jdbc.internal.common.query.MySQLParameterizedQuery.validate(MySQLParameterizedQuery.java:137)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1032)
	at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:1028)
	at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:271)
	... 17 more
[(i)20180301.11:41:01.165 ~46] EventScheduler processes event InternalEvent.10024timeout
[(i)20180301.11:41:01.165 ~144] EngineDriver.T144 - starts processing
[(d)20180301.11:41:01.165 ~144] executeFlow: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>DELAY</EventType><WorkType>ACTIVITY</WorkType><WorkId>3</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>10024</WorkInstanceId><WorkOwnerId>10006</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><SecondaryWorkOwnerId>1</SecondaryWorkOwnerId><SecondaryWorkOwnerType>SLA</SecondaryWorkOwnerType><MasterRequestId>mdwapp-20180228-114032</MasterRequestId></EventMessage>
[(i)20180301.11:41:01.228 p203304457.10006 a3.10024] Activity in waiting status times out
[(i)20180301.11:41:01.244 ~144] Unchedules event InternalEvent.10024
[(i)20180301.11:41:01.291 p203304457.10006 a3.10024] Activity cancelled - Cancelled due to time out
[(i)20180301.11:41:01.306 p203304457.10006 t2.10671] Transition initiated from 3 to 4
[(i)20180301.11:41:01.322 ~45] Received and processed broadcast: {"ACTION":"INVALIDATE_EVENT","EVENT_NAME":"InternalEvent.10024","FROM":"localhost:8080"}
```

**Comment by magrawa** [comment]
Don,
I could not test the flow as you did in mdw-central  but I created a similar flow in mdw core and I could not reproduce the error.  Maybe I need to test it in central. If I understood correctly the issues comes when event wait expires and take a delay path we get this error. Here are the logs from my testing:

[(d)20180308.10:56:25.033 ~76] >> POST request 112837 over REST on path 'Processes/run/com.centurylink.mdw.tests.workflow/MDWTestEventWaitTimeout'
[(i)20180308.10:56:25.050 p19856360.14691 m.manoj.agrawal@centurylink.com-20180308-105623] Process started - com.centurylink.mdw.tests.workflow/MDWTestEventWaitTimeout/0.10
[(d)20180308.10:56:25.053 ~76] Send JMS message: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>START</EventType><WorkType>ACTIVITY</WorkType><WorkId>2</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>0</WorkInstanceId><WorkOwnerId>14691</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><MasterRequestId>manoj.agrawal@centurylink.com-20180308-105623</MasterRequestId><WorkCompletionCode>START:</WorkCompletionCode></EventMessage>
[(i)20180308.10:56:27.508 ~184] EngineDriver.T184 - starts processing
[(d)20180308.10:56:27.508 ~184] executeFlow: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>START</EventType><WorkType>ACTIVITY</WorkType><WorkId>2</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>0</WorkInstanceId><WorkOwnerId>14691</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><MasterRequestId>manoj.agrawal@centurylink.com-20180308-105623</MasterRequestId><WorkCompletionCode>START:</WorkCompletionCode></EventMessage>
[(i)20180308.10:56:27.525 p19856360.14691 a2.27548] Activity started - Start
[(i)20180308.10:56:27.535 p19856360.14691 a2.27548] Activity completed - completion code null
[(i)20180308.10:56:27.605 p19856360.14691 t1.23208] Transition initiated from 2 to 3
[(i)20180308.10:56:27.623 p19856360.14691 a3.27549] Activity started - Event Wait
[(i)20180308.10:56:27.631 ~184] registered event wait event='NonTaskAction-manoj.agrawal@centurylink.com-20180308-105623' actInst=27549 as broadcast-waiting
[(i)20180308.10:56:27.633 p19856360.14691 a3.27549] set activity timeout as 120 seconds
[(d)20180308.10:56:27.636 ~184] Send JMS message: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>DELAY</EventType><WorkType>ACTIVITY</WorkType><WorkId>3</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>27549</WorkInstanceId><WorkOwnerId>14691</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><SecondaryWorkOwnerId>1</SecondaryWorkOwnerId><SecondaryWorkOwnerType>SLA</SecondaryWorkOwnerType><MasterRequestId>manoj.agrawal@centurylink.com-20180308-105623</MasterRequestId></EventMessage>
[(i)20180308.10:56:27.645 p19856360.14691 a3.27549] Activity suspended
webpack compile time: 10775 ms
[(i)20180308.10:58:28.010 ~193] EngineDriver.T193 - starts processing
[(d)20180308.10:58:28.010 ~193] executeFlow: <EventMessage xmlns="http://mdw.centurylink.com/bpm"><EventType>DELAY</EventType><WorkType>ACTIVITY</WorkType><WorkId>3</WorkId><WorkTransitionInstanceId>0</WorkTransitionInstanceId><WorkInstanceId>27549</WorkInstanceId><WorkOwnerId>14691</WorkOwnerId><WorkOwnerType>PROCESS_INSTANCE</WorkOwnerType><SecondaryWorkOwnerId>1</SecondaryWorkOwnerId><SecondaryWorkOwnerType>SLA</SecondaryWorkOwnerType><MasterRequestId>manoj.agrawal@centurylink.com-20180308-105623</MasterRequestId></EventMessage>
[(i)20180308.10:58:28.026 p19856360.14691 a3.27549] Activity in waiting status times out
[(i)20180308.10:58:28.031 ~193] Unchedules event InternalEvent.27549
[(i)20180308.10:58:28.420 p19856360.14691 a3.27549] Activity cancelled - Cancelled due to time out
[(i)20180308.10:58:28.421 ~60] Received and processed broadcast: {"ACTION":"INVALIDATE_EVENT","EVENT_NAME":"InternalEvent.27549","FROM":"localhost:8080"}
[(i)20180308.10:58:28.425 p19856360.14691 t3.23209] Transition initiated from 3 to 8
[(i)20180308.10:58:28.538 p19856360.14691 a8.27550] Activity started - Expired
[(i)20180308.10:58:28.544 p19856360.14691 a8.27550] Activity completed - completion code null
[(i)20180308.10:58:28.664 p19856360.14691 m.manoj.agrawal@centurylink.com-20180308-105623] Process completed - com.centurylink.mdw.tests.workflow/MDWTestEventWaitTimeout completion code is null
