### ISSUE TITLE
Persist request/meta for REST requests without a body

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#370]
Currently GET and DELETE requests that are mapped to a process with a "request" variable cause this:
```
[(i)20180402.18:09:38.901 p29029216.10208 a1.10818] Activity started - Start
[(s)20180402.18:09:38.902 ~82] Document with ID 0 does not exist
com.centurylink.mdw.dataaccess.DataAccessException: Document with ID 0 does not exist
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.getDocument(ProcessExecutorImpl.java:228)
	at com.centurylink.mdw.services.process.ProcessExecutor.getDocument(ProcessExecutor.java:703)
	at com.centurylink.mdw.services.process.BaseActivity.getDocument(BaseActivity.java:912)
	at com.centurylink.mdw.services.process.BaseActivity.getVariableValue(BaseActivity.java:1294)
	at com.centurylink.mdw.services.process.BaseActivity.prepare(BaseActivity.java:144)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivitySub(ProcessExecutorImpl.java:846)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivityInstance(ProcessExecutorImpl.java:751)
	at com.centurylink.mdw.services.process.ProcessExecutor.prepareActivityInstance(ProcessExecutor.java:319)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:332)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:612)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:844)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:754)
	at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:692)
	at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:972)
	at com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:264)
	at pets.Pets.get(Pets.java:50)
	at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:92)
	at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:59)
	at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:99)
	at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:408)
	at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:265)
	at com.centurylink.mdw.hub.servlet.RestServlet.doGet(RestServlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:230)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:333)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Document with ID 0 does not exist
	at com.centurylink.mdw.dataaccess.db.CommonDataAccess.loadDocument(CommonDataAccess.java:520)
	at com.centurylink.mdw.dataaccess.db.CommonDataAccess.getDocument(CommonDataAccess.java:469)
	at com.centurylink.mdw.service.data.process.EngineDataAccessCache.getDocument(EngineDataAccessCache.java:136)
	at com.centurylink.mdw.services.process.ProcessExecutorImpl.getDocument(ProcessExecutorImpl.java:226)
	... 52 more
```

**Comment by jbrojdeCTL** [comment]
We already persist the META for requests without a body.  Since there is nothing to persist in terms of a request body in these cases, we now will simply not try to bind the non-existing request (docId=0) to the "request" process variable when starting a process instance.
