### ISSUE TITLE
Docker image has "Could not load J2V8 library" error

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#393]
The current Docker image cannot load the J2V8 library, so things using React, like filepanel, do not work.
Error is:
java.lang.IllegalStateException: J2V8 native library not loaded
        at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:252)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:152)
        at com.eclipsesource.v8.V8.createV8Runtime(V8.java:128)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:84)
        at com.eclipsesource.v8.NodeJS.createNodeJS(NodeJS.java:48)
        at com.centurylink.mdw.node.WebpackCache.compile(WebpackCache.java:230)
        at com.centurylink.mdw.node.WebpackCache.doCompile(WebpackCache.java:205)
        at com.centurylink.mdw.node.WebpackCache.access$200(WebpackCache.java:54)
        at com.centurylink.mdw.node.WebpackCache$1.run(WebpackCache.java:189)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
        no libj2v8_linux_x86_64.so in java.library.path
        no j2v8_linux_x86_64 in java.library.path

**Comment by jbrojdeCTL** [comment]
The issue is that the user specified at runtime via --user flag for "docker run" command doesn't exist inside the container, and the current version of the j2v8 JAR file in our node asset package uses the system property "user.home" to extract the j2v8 native library file to, whichit cannot do if there is no home directory for the user.    Added new -D property to sample docker run command in docker guide:  -Duser.home=/usr/local/tomcat/temp

If we upgrade to a newer version of j2v8 JAR, it appears it might use "java.io.tmpdir" system property instead, which should work without the need for the additional -D property.
