### ISSUE TITLE
Asset auto pull fails if target directory not present

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#528]
```
 [(s)20181009.23:59:41.170 ~25] Error during Git up-to-date check.
com.centurylink.mdw.cache.CachingException: Directory does not exist: /repos/mdw-demo/assets
	at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:99)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:66)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackages(PackageCache.java:72)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.openConnection(DatabaseAccess.java:255)
	at com.centurylink.mdw.dataaccess.DbAccess.&lt;init&gt;(DbAccess.java:35)
	at com.centurylink.mdw.dataaccess.DbAccess.&lt;init&gt;(DbAccess.java:30)
	at com.centurylink.mdw.dataaccess.DataAccess.getAssetVersionControl(DataAccess.java:184)
	at com.centurylink.mdw.dataaccess.DataAccess.getVcsProcessLoader(DataAccess.java:101)
	at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:63)
	at com.centurylink.mdw.dataaccess.DataAccess.getProcessLoader(DataAccess.java:71)
	at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:78)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackageList(PackageCache.java:66)
	at com.centurylink.mdw.cache.impl.PackageCache.getPackages(PackageCache.java:72)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.openConnection(DatabaseAccess.java:255)
	at com.centurylink.mdw.dataaccess.DbAccess.&lt;init&gt;(DbAccess.java:35)
	at com.centurylink.mdw.dataaccess.DbAccess.&lt;init&gt;(DbAccess.java:30)
	at com.centurylink.mdw.dataaccess.DatabaseAccess.checkAndUpgradeSchema(DatabaseAccess.java:218)
	at com.centurylink.mdw.hub.MdwMain.startup(MdwMain.java:78) 
 	at com.centurylink.mdw.boot.servlet.StartupListener.contextInitialized(StartupListener.java:53)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4790)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1421)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1411)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: Directory does not exist: /repos/mdw-demo/assets
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.getPackageDirs(LoaderPersisterVcs.java:190)
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.getPackageDirs(LoaderPersisterVcs.java:184)
	at com.centurylink.mdw.dataaccess.file.LoaderPersisterVcs.getPackageList(LoaderPersisterVcs.java:810)
	at com.centurylink.mdw.cache.impl.PackageCache.load(PackageCache.java:78)
	... 27 more 
```

**Comment by donaldoakes** [comment]
Not an issue
