### ISSUE TITLE
Parsing exceptions due to slf4j logging

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#573]
Stack trace below.

This fix should be worked in conjunction with issue #571.  We need a more unique alternative to:
```java
private static final String MESSAGE_REG_EX = "\\[~mdw p([0-9]+)\\.([0-9]+) ([a-z])([0-9]+)?\\.([^]]+)] (.*)";
```
AbstractStandardLoggerBase.buildJSONLogMessage() and Log Watchers like Hub's Test Case watcher expect and match on this pattern, so we need to thoroughly test that features like Autotest updates in Hub, LiveView in Hub and test case Stubbing are still functional.

```
Error building log watcher json for: '[(i)20181230.04:11:07.656 p92188394.4850448 m.venkateswararao.katta@centurylink.com-1230101107584] Process started - com.ctl.hc.ite.conversation/SendAsynchronousMessage/0.6' -> java.lang.NumberFormatException: For input string: ".220118E4.220118E4"
java.lang.NumberFormatException: For input string: ".220118E4.220118E4"
                at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
                at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
                at java.lang.Double.parseDouble(Double.java:538)
                at java.text.DigitList.getDouble(DigitList.java:169)
                at java.text.DecimalFormat.parse(DecimalFormat.java:2089)
                at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1867)
                at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
                at java.text.DateFormat.parse(DateFormat.java:364)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.buildJSONLogMessage(AbstractStandardLoggerBase.java:91)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.sendToWatchers(AbstractStandardLoggerBase.java:139)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.logIt(AbstractStandardLoggerBase.java:231)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.info(AbstractStandardLoggerBase.java:243)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:820)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:754)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:693)
                at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:1009)
                at com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:215)
                at hc.api.Send.post(Send.java:73)
                at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:98)
                at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:58)
                at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:102)
                at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:397)
                at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:265)
                at com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:150)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
                at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:230)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:57)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:352)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.boot.servlet.WebContentFilter.doFilter(WebContentFilter.java:80)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
2018-12-30 04:11:07.697  INFO 1 --- [io-8080-exec-15] c.c.m.s.process.ProcessExecutorImpl      : [(i)20181230.04:11:07.697 p92188394.4850449 a1.2509990] Activity started - Receive Request
2018-12-30 04:11:07.697  INFO 1 --- [nio-8080-exec-7] c.c.m.s.process.ProcessExecutorImpl      : [(i)20181230.04:11:07.697 p92188394.4850448 a1.2509991] Activity started - Receive Request
Error building log watcher json for: '[(i)20181230.04:11:07.697 p92188394.4850449 a1.2509990] Activity started - Receive Request' -> java.lang.NumberFormatException: multiple points
Error building log watcher json for: '[(i)20181230.04:11:07.697 p92188394.4850448 a1.2509991] Activity started - Receive Request' -> java.lang.NumberFormatException: multiple points
java.lang.NumberFormatException: multiple points
                at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
                at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
                at java.lang.Double.parseDouble(Double.java:538)
                at java.text.DigitList.getDouble(DigitList.java:169)
                at java.text.DecimalFormat.parse(DecimalFormat.java:2089)
                at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1867)
                at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
                at java.text.DateFormat.parse(DateFormat.java:364)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.buildJSONLogMessage(AbstractStandardLoggerBase.java:91)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.sendToWatchers(AbstractStandardLoggerBase.java:139)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.logIt(AbstractStandardLoggerBase.java:231)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.info(AbstractStandardLoggerBase.java:243)
                at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivitySub(ProcessExecutorImpl.java:821)
                at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivityInstance(ProcessExecutorImpl.java:754)
                at com.centurylink.mdw.services.process.ProcessExecutor.prepareActivityInstance(ProcessExecutor.java:373)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:333)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:621)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:828)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:754)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:693)
                at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:1009)
                at com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:215)
                at hc.api.Send.post(Send.java:73)
                at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:98)
                at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:58)
                at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:102)
                at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:397)
                at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:265)
                at com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:150)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
                at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:230)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:57)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:352)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.boot.servlet.WebContentFilter.doFilter(WebContentFilter.java:80)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
java.lang.NumberFormatException: multiple points
                at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
                at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
                at java.lang.Double.parseDouble(Double.java:538)
                at java.text.DigitList.getDouble(DigitList.java:169)
                at java.text.DecimalFormat.parse(DecimalFormat.java:2089)
                at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1867)
                at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
                at java.text.DateFormat.parse(DateFormat.java:364)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.buildJSONLogMessage(AbstractStandardLoggerBase.java:91)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.sendToWatchers(AbstractStandardLoggerBase.java:139)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.logIt(AbstractStandardLoggerBase.java:231)
                at com.centurylink.mdw.util.log.AbstractStandardLoggerBase.info(AbstractStandardLoggerBase.java:243)
                at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivitySub(ProcessExecutorImpl.java:821)
                at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivityInstance(ProcessExecutorImpl.java:754)
                at com.centurylink.mdw.services.process.ProcessExecutor.prepareActivityInstance(ProcessExecutor.java:373)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:333)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:621)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:828)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:754)
                at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:693)
                at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:1009)
                at com.centurylink.mdw.services.rest.JsonRestService.invokeServiceProcess(JsonRestService.java:215)
                at hc.api.Send.post(Send.java:73)
                at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:98)
                at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:58)
                at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:102)
                at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:397)
                at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:265)
                at com.centurylink.mdw.hub.servlet.RestServlet.doPost(RestServlet.java:150)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
                at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:230)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:57)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:352)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at com.centurylink.mdw.boot.servlet.WebContentFilter.doFilter(WebContentFilter.java:80)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 ```

**Comment by jbrojdeCTL** [comment]
Root cause is that SimpleDateFormat class is not thread safe.
