### ISSUE TITLE
Startup race condition in TaskDataAccess results in query with duplicate columns

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#648]
Happens when the MDWHub Tasks tab is accessed while workgroup(s) referenced by some tasks don't exist in the environment.  The exception stack trace is below.  Instead of this we should return a 404 with a message about missing workgroups.
```
2019-06-07 10:23:17.963 ERROR 15757 --- [https-jsse-nio-17133-exec-2] c.c.m.s.handler.ServiceRequestHandler    : Failed to query task instances

com.centurylink.mdw.common.service.ServiceException: Failed to query task instances
	at com.centurylink.mdw.services.task.TaskServicesImpl.getTasks(TaskServicesImpl.java:149) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.service.rest.Tasks.get(Tasks.java:89) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.services.rest.JsonRestService.service(JsonRestService.java:93) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.services.rest.JsonRestService.getJson(JsonRestService.java:60) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.service.handler.ServiceRequestHandler.handleEventMessage(ServiceRequestHandler.java:92) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.listener.ListenerHelper.processEvent(ListenerHelper.java:438) [mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.hub.servlet.RestServlet.handleRequest(RestServlet.java:259) [mdw-spring-boot-6.1.19.jar!/:na]
	at com.centurylink.mdw.hub.servlet.RestServlet.doGet(RestServlet.java:76) [mdw-spring-boot-6.1.19.jar!/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at com.centurylink.mdw.hub.servlet.RestServlet.service(RestServlet.java:224) [mdw-spring-boot-6.1.19.jar!/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at com.centurylink.mdw.hub.servlet.CustomContentFilter.doFilter(CustomContentFilter.java:57) [mdw-spring-boot-6.1.19.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at com.centurylink.mdw.hub.servlet.AccessFilter.doFilter(AccessFilter.java:352) [mdw-spring-boot-6.1.19.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at com.centurylink.mdw.boot.servlet.WebContentFilter.doFilter(WebContentFilter.java:80) [mdw-spring-boot-6.1.19.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.32.jar!/:8.5.32]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: com.centurylink.mdw.dataaccess.DataAccessException: Failed to query task instances
	at com.centurylink.mdw.service.data.task.TaskDataAccess.getTaskInstances(TaskDataAccess.java:674) ~[mdw-services-6.1.19.jar!/:na]
	at com.centurylink.mdw.services.task.TaskServicesImpl.getTasks(TaskServicesImpl.java:138) ~[mdw-services-6.1.19.jar!/:na]
	... 56 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: ORA-00918: column ambiguously defined

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450) ~[na:na]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522) ~[na:na]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257) ~[na:na]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587) ~[na:na]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225) ~[na:na]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53) ~[na:na]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925) ~[na:na]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111) ~[na:na]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798) ~[na:na]
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845) ~[na:na]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501) ~[na:na]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83) ~[commons-dbcp2-2.1.1.jar!/:2.1.1]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83) ~[commons-dbcp2-2.1.1.jar!/:2.1.1]
	at com.centurylink.mdw.dataaccess.DatabaseAccess.logExecuteQuery(DatabaseAccess.java:335) ~[mdw-common-6.1.19.jar!/:na]
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runSelect(DatabaseAccess.java:421) ~[mdw-common-6.1.19.jar!/:na]
	at com.centurylink.mdw.dataaccess.DatabaseAccess.runSelect(DatabaseAccess.java:396) ~[mdw-common-6.1.19.jar!/:na]
	at com.centurylink.mdw.service.data.task.TaskDataAccess.getTaskInstances(TaskDataAccess.java:645) ~[mdw-services-6.1.19.jar!/:na]
	... 57 common frames omitted
```

**Comment by ab59451** [comment]
couldn't be reproduced.
 method tried 
deleted the  workgroup(s) configured for a manual task  from DB manually and tried to access the task.

**Comment by ab59451** [comment]
could not reproduce .

**Comment by donaldoakes** [comment]
Here's the errored SQL from logs captured when the error occurred:
```sql
select *from ( select allrows.*, rownum rnum from (
select distinct  ti.TASK_INSTANCE_ID,  ti.TASK_ID,  ti.TASK_INSTANCE_STATUS,  ti.TASK_INSTANCE_OWNER,  ti.TASK_INSTANCE_OWNER_ID,  ti.TASK_INST_SECONDARY_OWNER,  ti.TASK_INST_SECONDARY_OWNER_ID,  ti.TASK_CLAIM_USER_ID,  ti.TASK_START_DT,  ti.TASK_END_DT,  ti.COMMENTS,  ti.TASK_INSTANCE_STATE,  ti.TASK_INSTANCE_REFERRED_AS,  ti.DUE_DATE,  ti.PRIORITY,  ti.MASTER_REQUEST_ID, ti.TASK_TITLE, ti.TASK_TITLE,  ti.TASK_INSTANCE_OWNER_ID as PROCESS_INSTANCE_ID, ui.CUID, ui.NAME as USER_NAME
from TASK_INSTANCE ti, USER_INFO ui

where ui.user_info_id(+) = ti.task_claim_user_id
and ti.task_instance_status not in (4,5)
and ti.task_instance_state != 5
order by ti.task_instance_id desc, ti.task_id

) allrows where rownum <= 50) where rnum  > 0
```
