### ISSUE TITLE
Deleting a jar asset causes runtime problems

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#67]
Recently when we renamed a jar to mariaDB4j-db-osx-2.1.9.jar, after Git import we get the following error on server startup.  Apparently we don't handle well the situation where a jar asset exists in the Archive but not in the current assets.

```
java.io.FileNotFoundException: /opt/apache-tomcat-8/sd-workflow/assets/com/centurylink/mdw/db/mariaDB4j-db-mac-2.1.9.jar (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at com.centurylink.mdw.cloud.CloudClassLoader.findInJarFile(CloudClassLoader.java:205)
        at com.centurylink.mdw.cloud.CloudClassLoader.findInJarAssets(CloudClassLoader.java:240)
        at com.centurylink.mdw.cloud.CloudClassLoader.hasClass(CloudClassLoader.java:265)
        at com.centurylink.mdw.model.workflow.Package.getActivityImplementor(Package.java:507)
        at com.centurylink.mdw.services.process.ProcessExecutorImpl.prepareActivityInstance(ProcessExecutorImpl.java:720)
        at com.centurylink.mdw.services.process.ProcessExecutor.prepareActivityInstance(ProcessExecutor.java:230)
        at com.centurylink.mdw.services.process.ProcessEngineDriver.executeActivity(ProcessEngineDriver.java:332)
        at com.centurylink.mdw.services.process.ProcessEngineDriver.processEvent(ProcessEngineDriver.java:612)
        at com.centurylink.mdw.services.process.ProcessEngineDriver.executeServiceProcess(ProcessEngineDriver.java:830)
        at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:741)
        at com.centurylink.mdw.services.process.ProcessEngineDriver.invokeService(ProcessEngineDriver.java:679)
        at com.centurylink.mdw.services.workflow.WorkflowServicesImpl.invokeServiceProcess(WorkflowServicesImpl.java:913)
```

**Comment by jbrojdeCTL** [comment]
I think the issue here was that we were caching the list of JARs (per CloudClassLoader object instance), so if the file changed names, CloudClassLoader doesn't know about it.   I have moved the "caching" part into AssetCache class so that it can be re-generated when a cache refresh takes place.   

Is there an easy way to test this?

**Comment by jbrojdeCTL** [comment]
Ok, so issue was that we were building the path to the asset by concatenating assetRoot + "/" + jarAsset.getPackageName().replace('.', '/') + "/" + jarAsset.getName(), which won't work on any JAR file located in Archive folder since the path will always resolve to the path of the latest pkg, which means it would never search JARs in Archive sub folders.    I'm fixing this by making use of the Asset.getRawFile() method to retrieve the actual JAR file instead of trying to build a new File with a derived concatenated path.
