### ISSUE TITLE
CLI without command throws IndexOutOfBoundsException on Windows

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#807]
Running just `mdw` shows the following stack trace, whereas on Linux/Mac it displays the help message as expected.

```
C:\>mdw
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at com.centurylink.mdw.cli.Main.main(Main.java:81)
```

**Comment by naveena-bellamkonda** [comment]
unable to reproduce this issue with 6.1.32-SNAPSHOT cli.  Without command, it displays the version and help message.
