### ISSUE TITLE
When stubbing, sometimes message sent from client to stub server is missing last few characters

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#850]
When SoccomClient sends message to SoccomServer, it sends full message, but receiving end only reads most of message, resulting in exceptions trying to parse into a JSON object:

java.io.IOException: Unterminated string at 58217 [character 89 line 6]
	at com.centurylink.mdw.services.test.StubServer.requestProc(StubServer.java:123)
	at com.centurylink.mdw.soccom.SoccomServer.processMessage(SoccomServer.java:374)
	at com.centurylink.mdw.soccom.SoccomServer.startSub(SoccomServer.java:141)
	at com.centurylink.mdw.soccom.SoccomServer.access$000(SoccomServer.java:33)
	at com.centurylink.mdw.soccom.SoccomServer$1.run(SoccomServer.java:113)
Caused by: org.json.JSONException: Unterminated string at 58217 [character 89 line 6]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
	at org.json.JSONTokener.nextString(JSONTokener.java:320)
	at org.json.JSONTokener.nextValue(JSONTokener.java:428)
	at org.json.JSONObject.<init>(JSONObject.java:244)
	at org.json.JSONTokener.nextValue(JSONTokener.java:431)
	at org.json.JSONObject.<init>(JSONObject.java:244)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at io.limberest.json.JsonObject.<init>(JsonObject.java:25)
	at com.centurylink.mdw.model.JsonObject.<init>(JsonObject.java:35)
	at com.centurylink.mdw.services.test.StubServer.requestProc(StubServer.java:107)
	... 4 more

I think the buffer needs to be flushed on SoccomClient after performing write to socket output stream. (Tried this already, did not work as appearently flush() doesn't do anything for a SocketOutputStream)

This only happens on certain size of messages (large ones), and also only on certain machines, but it happens every time on same machine given same message.

**Comment by jbrojdeCTL** [comment]
The root cause is that when the message is built in SoccomMessage.java, the size of the message (as determined by calling length() method on String variable) is added to the header part of the message to be sent.   However, the actual resulting size in bytes (by calling getBytes() method) is not always the same, so when the receiving end reads the message, and gets the size of the body from the header, it does not read all the bytes that were sent.
